apiVersion: argoproj.io/v1alpha1
kind: Application  # This manifest (YAML file) creates an Argo CD app
metadata:
  name: jfremond-app
  namespace: argocd
spec:  # How Argo CD should manage the app
  project: default
  source:
    repoURL: https://github.com/jfremond/k3d-repo  # Git repo
    targetRevision: HEAD  # Git branch to track
    path: '.'  # Path inside the git repo
  destination: # Where to deploy the app
    namespace: dev
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    automated:  # Auto-sync enabled
      prune: true  # Remove Kubernetes resources not tracked in git repo
      selfHeal: true  # Reapply manifest to match git repo
