# -*- mode: ruby -*-
# vi: set ft=ruby :

USER = ENV['USER']

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # common virtualbox config
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1536 # 1.5 GB
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # master node config
  config.vm.define "#{USER}S" do |server|
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "#{USER}S"

    server.vm.provision "shell", path: "scripts/master.sh"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "#{USER}S"
    end
  end
end
