# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "bbrassarS" do |server|
    ip_address = "192.168.56.110"

    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: ip_address
    server.vm.hostname = "bbrassarS"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "bbrassarS"
      vb.cpus = 1
      vb.memory = 1024
    end

    server.vm.provision "shell", inline: <<-SHELL
      printf -- 'alias k=kubectl\n' | tee /etc/profile.d/kubectl.sh
    SHELL

    server.vm.provision "shell",
      path: "https://raw.githubusercontent.com/k3s-io/k3s/cca8facaa33a3ec7897349a8740fd96029590c31/install.sh", # https://github.com/k3s-io/k3s/releases/tag/v1.32.0+k3s1
      args: [
        "--cluster-init",
        "--flannel-backend=none",
        "--write-kubeconfig-mode=644",
        "--node-ip", ip_address,
        "--bind-address", ip_address,
      ],
      env: {
        "INSTALL_K3S_EXEC": "server",
      },
      sha512: "d26d80c7928c0a1bddad64db4b096f1c037e969f55e334842e16e2d9c9f34c8fe2b3e46a842a76f29fdb8daa930b9082ef7b25216e97f463c24fa02e5fd11b3c"
  end

  config.vm.define "bbrassarSW" do |server|
    ip_address = "192.168.56.111"

    server.vm.box = "debian/bookworm64"
    server.vm.network "private_network", ip: ip_address
    server.vm.hostname = "bbrassarSW"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "bbrassarSW"
      vb.cpus = 1
      vb.memory = 1024
    end
  end
end
