# -*- mode: ruby -*-
# vi: set ft=ruby :

USER = bbrassar

Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.synced_folder "./shared", "/vagrant_shared", create: true

  config.vm.provision "shell", privileged: true, path: "scripts/common.sh"

  # common virtualbox config
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1536 # 1.5 GB
    vb.cpus = 1
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
  end

  # master node config
  config.vm.define "#{USER}S" do |server|
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.hostname = "#{USER}S"

    server.vm.provision "shell", path: "scripts/master.sh"

    server.vm.provider "virtualbox" do |vb|
      vb.name = "#{USER}S"
    end
  end

  # worker node config
  config.vm.define "#{USER}SW" do |worker|
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.hostname = "#{USER}SW"

    worker.vm.provision "shell", path: "scripts/worker.sh"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "#{USER}SW"
    end
  end
end
